create table if not exists public.waiter_calls (
  id bigint generated by default as identity primary key,
  table_number integer,
  status text not null default 'new' check (status in ('new', 'handled')),
  page_url text,
  user_agent text,
  created_at timestamptz not null default now(),
  handled_at timestamptz
);

alter table public.waiter_calls enable row level security;

drop policy if exists "Guests can create waiter calls" on public.waiter_calls;
drop policy if exists "Staff board can read waiter calls" on public.waiter_calls;
drop policy if exists "Staff board can handle waiter calls" on public.waiter_calls;

create policy "Guests can create waiter calls"
on public.waiter_calls
for insert
to anon
with check (status = 'new');

create policy "Staff board can read waiter calls"
on public.waiter_calls
for select
to anon
using (true);

create policy "Staff board can handle waiter calls"
on public.waiter_calls
for update
to anon
using (true)
with check (status in ('new', 'handled'));

grant usage on schema public to anon;
grant select, insert, update on public.waiter_calls to anon;

do $$
begin
  alter publication supabase_realtime add table public.waiter_calls;
exception
  when duplicate_object then null;
end $$;
